version: '3'

vars:
  SOLUTION_FILE: DotNetStarterKit.sln
  API_PROJECT: WebAPI
  API_APPSETTINGS_DEV: WebAPI/appsettings.Development.json

tasks:
  setup:
    desc: Initial project setup - restore packages and create development appsettings
    cmds:
      - dotnet restore {{.SOLUTION_FILE}}
      - task: create-dev-appsettings
    
  create-dev-appsettings:
    desc: Create appsettings.Development.json if it doesn't exist
    cmds:
      - |
        if [ ! -f "{{.API_APPSETTINGS_DEV}}" ]; then
          echo "Creating {{.API_APPSETTINGS_DEV}}..."
          cat > {{.API_APPSETTINGS_DEV}} << 'EOF'
        {
          "Logging": {
            "LogLevel": {
              "Default": "Information",
              "Microsoft.AspNetCore": "Warning"
            }
          },
          "AllowedHosts": "*",
          "CrudFactory": {
            "Implementation": "InMemory"
          },
          "FileData": {
            "Directory": "data"
          }
        }
        EOF
          echo "Created {{.API_APPSETTINGS_DEV}}"
        else
          echo "{{.API_APPSETTINGS_DEV}} already exists"
        fi
    status:
      - test -f {{.API_APPSETTINGS_DEV}}

  build:
    desc: Build the entire solution
    cmds:
      - dotnet build {{.SOLUTION_FILE}}

  clean:
    desc: Clean build artifacts
    cmds:
      - dotnet clean {{.SOLUTION_FILE}}

  test:
    desc: Run all unit tests
    cmds:
      - dotnet test {{.SOLUTION_FILE}}

  run:
    desc: Run the WebAPI project
    dir: "{{.API_PROJECT}}"
    cmds:
      - dotnet run

  run-dev:
    desc: Run the WebAPI project with Development environment
    dir: "{{.API_PROJECT}}"
    env:
      ASPNETCORE_ENVIRONMENT: Development
    cmds:
      - dotnet run

  restore:
    desc: Restore NuGet packages
    cmds:
      - dotnet restore {{.SOLUTION_FILE}}

  watch:
    desc: Run the WebAPI project with file watching (auto-restart on changes)
    dir: "{{.API_PROJECT}}"
    env:
      ASPNETCORE_ENVIRONMENT: Development
    cmds:
      - dotnet watch run

  help:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  default:
    desc: Show help by default
    cmds:
      - task help
    silent: true